### ISSUE TITLE
structurizr-cli-1.4.5.zip has been changed after release

### ISSUE THREAD

**Issue by bayandin** [structurizr/cli#10]
Hello,

I'm homebrew maintainer and have noticed that file `structurizr-cli-1.4.5.zip` attached to release artefacts has been changed,
Initially it it was `SHA256: 12d14971cb1436830ccfa703f0c699ba07058ff52d923ece34aa81cdbb447adf`, 
now it's `SHA256: 67135390e1c14286300d6d62985ebf4739b01f3a03da7dfe129f3f25f4c7eb15 `.
(it looks like the later version contains changes from https://github.com/structurizr/cli/commit/1866a453b3d39af3d19a3f7435fae28b9295d57b)

Could you please confirm that file `structurizr-cli-1.4.5.zip` was changed intentionally and not as a result of some malicious activity? That will allow me to update the checksum in homebrew.

Thanks!

**Comment by simonbrowndotje** [comment]
Yes, that was me ... sorry!

**Comment by bayandin** [comment]
> Yes, that was me ... sorry!

No problem, I will update a checksum in https://github.com/Homebrew/homebrew-core/pull/62775.
