### ISSUE TITLE
c4plantuml.stdlib property not working on cli 1.20.1

### ISSUE THREAD

**Issue by dzeigler** [structurizr/cli#102]
I'm trying to use the c4plantuml.stdlib property with the cli 1.20.1 release in my Gradle/Jenkins build, but the generated puml file still uses the GitHub URL. I think this is because cli is using an older version of the export dependency that doesn't support the property yet. I confirmed the same dsl worked as expected on structurizr web. 

Would it be possible to get a new release with updated dependencies to support that property?

**Comment by dzeigler** [comment]
Thanks. I'll try to get that approach working. It would still be nice to have a new release version number for cli for a couple reasons. 

1. The gradle-structurizr-cli plug-in seems to only support downloading tagged, versioned releases. I'll try to work around that limitation for now and may request support be added for downloading the latest from the URL you provided. That may come with caching issues though, as the plugin tries not to download the same version if it has already in the past. 
2. Having a versioned artifact as a dependency helps make our builds behave more deterministically. 

Thanks again!

**Comment by simonbrowndotje** [comment]
GitHub releases will be coming back soon. :-)

**Comment by simonbrowndotje** [comment]
https://github.com/structurizr/cli/releases/tag/v1.24.0 is now available.
