### ISSUE TITLE
Inconsistent plantuml names

### ISSUE THREAD

**Issue by dgutson** [structurizr/cli#103]
With the latest version (1.8.4, and I think this is the exporter repo) naming changed completely and broke all my build system.
I sometimes use the C4-plantUML exporter, and sometimes the structurizr plantUML (should I distinguish which one in each case? It's quite a lot of work).
This is an example of what I get now:
![image](https://user-images.githubusercontent.com/9671770/216783851-ac6524d7-bb3c-4ea4-a9bd-a1e984478378.png)

Trying to get a pattern, seems that dynamic diagrams (structurizr plantUML) preserves the name, whereas C4 lost the names and just gets enumerated. [EDIT] No, this is not correct.

I always explicit a view key.

Also note that these changes are breaking changes when structurizr is used in a build system as we have.

**Comment by simonbrowndotje** [comment]
The naming of exported files is done by the CLI ([ExportCommand.java#L169](https://github.com/structurizr/cli/blob/b19e8871876a3597bf021dc19c384978a148e208/src/main/java/com/structurizr/cli/export/ExportCommand.java#L169)), and uses the `key` associated with the view. It looks like you're seeing the side-effect of [this bug fix to the DSL parser](https://github.com/structurizr/dsl/commit/17026e76675913e5a7ee8dac4e150773bc53742c). If you want to ensure the naming consistency of your exported files, you'll need to make your view keys explicit when you define your views.

i.e.

```
systemLandscape "mykey" {
...
}
```

vs

```
systemLandscape {
...
}
```
