### ISSUE TITLE
Latest version to download structurizr-cli

### ISSUE THREAD

**Issue by bitsmuggler** [structurizr/cli#104]
Hi

I'm looking for a static link to download the latest structurizr-cli for my [software architecture documentation example](https://github.com/bitsmuggler/arc42-c4-software-architecture-documentation-example).

So far I'm using the following link:

`https://static.structurizr.com/download/structurizr-cli.zip`

Unfortunately, I get `Access Denied`.

I see that I can download a specific version via GitHub. But is there a latest version for local installation? 

That would be great for my example...:-)

Thanks for your help and this great architecture documentation tool suite!

Kind regards, Patrick

**Comment by simonbrowndotje** [comment]
Releases have moved back to GitHub -> https://github.com/structurizr/cli/releases

**Comment by bitsmuggler** [comment]
OK, thanks for your answer.
