### ISSUE TITLE
Documentation scope

### ISSUE THREAD

**Issue by florianmutter** [structurizr/cli#11]
Is it possible to add documentation to a different scope than the workspace with the cli? In the web ui the scope can be chosen from a drop down menu.

![grafik](https://user-images.githubusercontent.com/32459530/98360037-72667f80-2029-11eb-84ca-b2dbd3f4f2b9.png)

**Comment by simonbrowndotje** [comment]
Are you using the DSL in conjunction with the CLI?

**Comment by florianmutter** [comment]
Yes

**Comment by simonbrowndotje** [comment]
A new version of the CLI will be released next week, including support for `!docs <path>`, which you'll be able to use to attach a directory of documentation to an individual software system (or the workspace).

**Comment by simonbrowndotje** [comment]
This is now supported in [v1.5.0](https://github.com/structurizr/cli/releases/tag/v1.5.0).
