### ISSUE TITLE
"dsl" not a supported output format, contradicting docs

### ISSUE THREAD

**Issue by tiilikainen** [structurizr/cli#115]
### Description

The [export readme](https://github.com/structurizr/export/blob/main/README.md) lists "dsl" as a valid output format:

> dsl: extracts the DSL that was used to create a JSON workspace

However, running the export command with the `dsl` format type produces an error.

Was this feature planned and then not implemented, or implemented and then removed?

### Steps to reproduce

1. Install `structurizr-cli` via Homebrew
2. Run `structurizr-cli` with parameters detailed below
3. View error output

### Code sample

```text
$ structurizr-cli export -w workspace.json -f dsl
Exporting workspace from workspace.json
 - loading workspace from JSON
 - no views defined; creating default views
 - unknown export format: dsl
 - unknown export format: dsl
 - finished
```

### Configuration

```
$ structurizr-cli help
structurizr-cli: 1.30.0
structurizr-java: 1.24.0
structurizr-dsl: 1.30.0
structurizr-export: 1.14.0
structurizr-import: v1.4.1
```

### Severity

Minor

### Priority

Low

### Resolution

I have no budget, please fix this for free

**Comment by pcolby** [comment]
This has been broken since v1.26.0 - ie works (work for) on v1.25.0, but no later.
