### ISSUE TITLE
Structurizr as a dev container feature

### ISSUE THREAD

**Issue by ThePlenkov** [structurizr/cli#123]
### Description

Hi! It would be nice if instead of using prebuild containers we could use devcontainer feature (https://containers.dev/features). In this case we can keep using our devcontianer images but with preinstalled CLI.

### Priority

Low

### Resolution

I have no budget, please add this feature for free

**Comment by simonbrowndotje** [comment]
You might be interested in https://github.com/evilpilaf/structurizr-remotecontainer (linked to from https://github.com/structurizr/cli/blob/master/docs/containers.md).

**Comment by ThePlenkov** [comment]
well - indeed - I understand what you mean, but here is the point. The root container may be different . Someones writes java, someone uses Node, we all use different base containers. But feature approach allows us to share features among base containers actually

**Comment by simonbrowndotje** [comment]
Dev containers isn't something that I use, but you're welcome to add support.
