### ISSUE TITLE
Suggestion: warn when pushing with no model

### ISSUE THREAD

**Issue by kirkj** [structurizr/cli#15]
Hi,

I had a confusing 5 minutes where I couldn't figure out why my pushed model wasn't updating in the web UI:

```
$ structurizr.sh push -id 60SNIP -key SNIP -secret SNIP demo.model
Structurizr CLI v1.5.0
Pushing workspace 60688 to https://api.structurizr.com
 - pulling existing workspace 60688 from https://api.structurizr.com
 - pushing workspace
 - finished
```

It looked like it was working, but the workspace didn't change.

The issue was that I was just putting the filename on the end without the `-workspace` option ahead of it. The correct command line I should have used was: 

`$ structurizr.sh push -id 60SNIP -key SNIP -secret SNIP -workspace demo.model`

So this issue is a suggestion to warn if the push command executes with no new model provided, and perhaps to also warn if there are unexpected command line arguments.

Thanks!

Kirk

**Comment by simonbrowndotje** [comment]
Thanks!
