### ISSUE TITLE
/bin/bash: line 1: structurizr.sh: command not found

### ISSUE THREAD

**Issue by cnd5041** [structurizr/cli#156]
### Description

In our build, we are running `structurizr.sh validate -workspace structurizr/workspace.dsl`. 

After the latest build, we get the error `/bin/bash: line 1: structurizr.sh: command not found`. 

Likely related to his commit: https://github.com/structurizr/cli/commit/0d22ed18b56f684eab8d517a072a414a26ef6c62, and the change of entry point. 

Related docs: https://docs.structurizr.com/cli/validate

### Steps to reproduce

`structurizr.sh validate -workspace structurizr/workspace.dsl`. 

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

### More information

PSA in case it breaks for anybody else.

**Comment by simonbrowndotje** [comment]
It works for me:

```
curl https://github.com/structurizr/cli/releases/download/2024.01.02/structurizr-cli.zip -L -o structurizr-cli.zip
unzip structurizr-cli.zip
./structurizr.sh version
```

Output
```
structurizr-cli: 2024.01.02
structurizr-java: 1.29.0
structurizr-dsl: 1.35.0
structurizr-export: 1.19.0
structurizr-import: v1.7.0
Java: 20.0.1/Oracle Corporation (/Library/Java/JavaVirtualMachines/jdk-20.jdk/Contents/Home)
OS: Mac OS X 13.5.2 (aarch64)
```

**Comment by cc-stjm** [comment]
If it helps, I think the issue is that structurizr.sh isn't in the path for the docker image. /usr/local/structurizr-cli/structurizr.sh is the path within the docker image.
