### ISSUE TITLE
Structurizr CLI: "Authorization header doesn't match" when pushing to structurizr on-prem docker using the -branch argument

### ISSUE THREAD

**Issue by chris-core** [structurizr/cli#165]
### Expected

``` 
- pushing workspace
Putting workspace with ID 1
{"success":true,"message":"OK"}
 - finished
```

### Actual

```
- pushing workspace
Putting workspace with ID 1
com.structurizr.api.StructurizrClientException: Authorization header doesn't match
com.structurizr.api.StructurizrClientException: com.structurizr.api.StructurizrClientException: Authorization header doesn't match
	at com.structurizr.api.WorkspaceApiClient.putWorkspace(WorkspaceApiClient.java:351)
	at com.structurizr.cli.PushCommand.run(PushCommand.java:137)
	at com.structurizr.cli.StructurizrCliApplication.run(StructurizrCliApplication.java:83)
	at com.structurizr.cli.StructurizrCliApplication.main(StructurizrCliApplication.java:104)
Caused by: com.structurizr.api.StructurizrClientException: Authorization header doesn't match
	at com.structurizr.api.WorkspaceApiClient.putWorkspace(WorkspaceApiClient.java:346)
	... 3 more
```

### Steps to reproduce

With the following structurizr.properties configuration in the /Users/chris-core/structurizr-on-prem directory:
```
structurizr.feature.ui.dslEditor=false
structurizr.feature.workspace.branches=true
structurizr.feature.diagramReviews=false
```

Start a structurizr/on-premises instance via docker using latest tag:
`docker run --name structurizr-on-prem -it --rm -p 8081:8080 -v /Users/chris-core/structurizr-on-prem:/usr/local/structurizr structurizr/onpremises`

Note that on starting structurizr on-prem, logger also writes the below line, despite structurizr.properties contents:
`ContextLoaderListener - Workspace branches: false`

Visit localhost:8081, create a workspace, note workspace ID / API Key / Secret.

From a directory containing any workspace.dsl file, use latest tag structurizr/cli docker container attached to structurizr-on-prem docker container network to push workspace.dsl to structurizr on-prem, using -branch main argument:
`docker run --network container:structurizr-on-prem -it --rm -v $PWD:/usr/local/structurizr structurizr/cli push -branch main -merge false -archive false -url http://localhost:8080/api -id 1 -key [API_KEY] -secret [API_SECRET] -workspace workspace.dsl`

The above command fails with `com.structurizr.api.StructurizrClientException: Authorization header doesn't match`.

Running the same command without the argument `-branch main` succeeds.

### Version/build information

structurizr/onpremises docker container, latest tag as of 20/11/2024
>ContextLoaderListener - Structurizr on-premises installation
ContextLoaderListener -  - build: 2024.11.05 (2024-11-05T12:06:00Z)
ContextLoaderListener -  - structurizr-java: v3.1.0
ContextLoaderListener -  - structurizr-dsl: v3.1.0
ContextLoaderListener -  - structurizr-import: v3.1.0
ContextLoaderListener -  - structurizr-graphviz: v3.1.0

structurizr/cli docker container, latest tag as of 20/11/2024
`$ docker run -it --rm structurizr/cli version`
>structurizr-cli: 2024.11.04
structurizr-java: 3.1.0
Java: 21.0.5/Eclipse Adoptium (/opt/java/openjdk)
OS: Linux 6.10.11-linuxkit (aarch64)

### Severity

Minor

### Priority

I have no budget and there's no rush, please fix this for free

### More information

Happy to provide any other information that is useful, looking forward to using the branch features and thank you for building such a great tool.

**Comment by simonbrowndotje** [comment]
You'll need to build from source or use an early access build to use the workspace branching feature. See https://docs.structurizr.com/onpremises/workspace-branches for details.

**Comment by chris-core** [comment]
Ah, thank you, I must have missed that line on the branching page. Reading the on-prem documentation regarding [configuration](https://docs.structurizr.com/onpremises/configuration), I had assumed the feature made it into GA.
