### ISSUE TITLE
Revert to previous version

### ISSUE THREAD

**Issue by lhohan-cb** [structurizr/cli#31]
I used the CLI to push a version from a different git branch (with quite some difference, also new diagrams).
This caused the layout to be completely lost for at least some of the diagrams.

I can load a previous version in the structurizr web viewer but cannot revert to it because I have uploaded a newer version (400 error).

Is there a way to handle this situation relatively easily?
What would be the recommended approach to handle or avoid this situation?
Can I download the formatting information and merge it locally somehow? 
I think it would help 'forcing' to restore a previous version on the web interface and then start pushing to that again. That is what I tried initially but I ran into the 400 error. 

For now I am reverting to manually redrawing the diagrams but I can imagine this happening again and is quite some work.

**Comment by simonbrowndotje** [comment]
> I can load a previous version in the structurizr web viewer but cannot revert to it because I have uploaded a newer version (400 error).

This should be working again now ... somebody else raised the same issue on Friday, and it was fixed, but not released.

**Comment by lhohan-cb** [comment]
> > I can load a previous version in the structurizr web viewer but cannot revert to it because I have uploaded a newer version (400 error).
> 
> This should be working again now ... somebody else raised the same issue on Friday, and it was fixed, but not released.

Thank you, good to know reverting should have worked.
I'll find out next time if it works :)
