### ISSUE TITLE
shape of styles is not being applied 

### ISSUE THREAD

**Issue by philcruz** [structurizr/cli#36]
If I have a dsl with the basic getting started

```
workspace "Getting Started" "This is a model of my software system." {

	model {
		user = person "User" "A user of my software system."
		softwareSystem = softwareSystem "Software System" "My software system."

		user -> softwareSystem "Uses"
	}

	views {
		systemContext softwareSystem "SystemContext" "An example of a System Context diagram." {
				include *
				autoLayout
		}

		styles {
			element "Software System" {
					background #1168bd
					color #ffffff
			}
			element "Person" {
					shape person
					background #08427b
					color #ffffff
			}
		}
	}

}
```

and I export that to plantUML, all the shapes are rectangles. The user is not rendered with a Person shape. What is the issue?

**Comment by philcruz** [comment]
Hmm....if you use that dsl on https://structurizr.com/dsl it renders the Person shape. But if you use the option to export to plantulm and render the plantuml it just renders as rectangles.

**Comment by simonbrowndotje** [comment]
Some export formats do not support all of the available shapes/features - see [Structurizr - Rendering tools](https://structurizr.org/#rendering) for a comparison.

**Comment by philcruz** [comment]
Ah, ok. Thanks for the clarification.
