### ISSUE TITLE
Seems to ignore autoLayout for dynamic views

### ISSUE THREAD

**Issue by DavidGregory084** [structurizr/cli#4]
Hi! This is a really awesome project! I don't think I have found anything else that makes it quite so easy to put together these kinds of diagrams.

One thing I have noticed is that when exporting a dynamic view to PlantUML, it seems like the CLI ignores the `autoLayout` keyword. I am using the v1.4.1 jar.

You can see an example of this in [this file](https://github.com/DavidGregory084/inc/blob/master/architecture/inc.dsl). I have declared `autoLayout tb` but the generated PlantUML file is always in `left to right direction`.

Apologies if this is the wrong project, wasn't sure whether to raise this here or in structurizr/dsl.

**Comment by simonbrowndotje** [comment]
Thanks for the kind words, glad you're finding the project useful! This is fixed in 1.4.2 of the CLI.
