### ISSUE TITLE
1.10.1 missing on maven-central

### ISSUE THREAD

**Issue by cachescrubber** [structurizr/cli#42]
Hi Simon,

while upgrading my poms to the latest structurizr version (1.10.1) I noticed the last version on public maven repos is v 1.9.2 uploaded 27-Apr-2021: https://search.maven.org/artifact/com.structurizr/structurizr-client. Something wrong?

Best,
Lars

**Comment by simonbrowndotje** [comment]
That's correct ... v1.9.2 is the current version of the Structurizr for Java client library.

**Comment by cachescrubber** [comment]
Sorry, I confused cli with java -client.
