### ISSUE TITLE
workspace path ... does not exist

### ISSUE THREAD

**Issue by Berkmann18** [structurizr/cli#44]
I'm trying to `push` a DSL (named `current-sys.dsl`) and I get the following output:
```
Pushing workspace 63929 to https://api.structurizr.com
 - workspace path current-sys.dsl does not exist
```
I've got the JSON files fetched by `pull` but those are outdated.
That seems to be a regression given that pushing DSLs with the CLI on ArchLinux worked last time I tried (with an older version tho, given the CLI hasn't been ported to any of the Linux package managers).
Edit: A similar issue happens with the `export` command.

## System
- CLI version: v1.11.0
- Terminal: WSL 2.0 (Ubuntu 20.04)

Unrelated but it seems that there's a discrepancy in the `workspace` arguments across commands where `validate`/`list` have `-w, --workspace` but not `pull`/`push` which have `-workspace, --workspace`.

**Comment by simonbrowndotje** [comment]
Are you running the version available from the releases page here (i.e. natively on your computer), or via another package (e.g. Docker)?

**Comment by Berkmann18** [comment]
@simonbrowndotje Yup, I downloaded the zip from the releases.

**Comment by simonbrowndotje** [comment]
Does this work with the newer versions?

**Comment by Berkmann18** [comment]
Yup.
