### ISSUE TITLE
Please provide a way to generate diagrams locally, without uploading to any cloud service.

### ISSUE THREAD

**Issue by venthur** [structurizr/cli#47]
It would be very nice if the CLI could operate completely locally: you provide a `.dsl` file and it spits out several `.png` (or similar) files. Since it seems graphviz based it shouldn't be strictly required to create a structurizr account and upload files for processing there, right?

**Comment by simonbrowndotje** [comment]
The Structurizr renderer creates diagrams client-side (i.e. in the web browser), so it's not possible to generate them via the CLI. Some options you have:

- Use the CLI to export to PlantUML, and generate PNGs locally using that toolchain. 
- Use [Structurizr Lite](https://structurizr.com/help/lite) - a free Docker-based version of Structurizr that can be run locally.

The Structurizr renderer can be used in conjunction with headless Chrome and Puppeteer (here are some [example scripts](https://github.com/structurizr/puppeteer)) to generate PNGs via the command line. A paid cloud service subscription will give you [directly embeddable PNGS](https://structurizr.com/help/embed-image) too.

**Comment by simonbrowndotje** [comment]
[structurizr-to-png](https://github.com/extenda/structurizr-to-png) might also be useful if you want to go down the PlantUML route.
