### ISSUE TITLE
Sample workspace JSON generates jackson exception structurizr-cli-1.12.1.jar

### ISSUE THREAD

**Issue by nicodewet** [structurizr/cli#48]
Checked out master, did build and copy jar to etc ( ./gradlew bootJar && cp build/libs/structurizr-cli-1.12.1.jar etc/) then with 
sample / starter example I get:  

`com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'workspace': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')`

Upload as follows: ./etc/structurizr.sh push -id <id> -key KEY -secret <secret> -workspace structurizr-model.json

Simple example from actual structurizr docs: 

`
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout
        }

        theme default
    }

}
`

**Comment by simonbrowndotje** [comment]
That example isn't JSON, it's the Structurizr DSL ... try renaming the file to `structurizr-model.dsl`.

**Comment by nicodewet** [comment]
My bad, yes this worked.

$ mv structurizr-model.json structurizr-model.dsl
