### ISSUE TITLE
Exporting to mermaid, plantuml, and possibly other types is broken

### ISSUE THREAD

**Issue by jerkstorecaller** [structurizr/cli#55]
I downloaded the latest binary (1.14.0) from the release pages and ran it on Ubuntu 20.04, using openjdk-16-jre from Ubuntu's repos, and tried to export the getting-started DSL.

**PlantUML fails**

```
$ ./structurizr.sh export -workspace examples/getting-started/workspace.dsl -format plantuml
Exporting workspace from examples/getting-started/workspace.dsl
 - loading workspace from DSL
 - using StructurizrPlantUMLExporter
 - writing /home/user/bin/structurizr-cli-1.14.0/examples/getting-started/structurizr-SystemContext.puml
 - finished

$ cat examples/getting-started/structurizr-SystemContext.puml 
@startuml
title Software System - System Context

top to bottom direction

skinparam {
  shadowing false
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
  PackageBorderColor<<group>> #cccccc
  PackageFontColor<<group>> #cccccc
}

hide stereotype

skinparam rectangle<<SoftwareSystem>> {
  BackgroundColor #1168bd
  FontColor #ffffff
  BorderColor #0b4884
}
skinparam person<<User>> {
  BackgroundColor #08427b
  FontColor #ffffff
  BorderColor #052e56
}

person "==User\n<size:10>[Person]</size>\n\nA user of my software system." <<User>> as User
rectangle "==Software System\n<size:10>[Software System]</size>\n\nMy software system." <<SoftwareSystem>> as SoftwareSystem

User .[#707070,thickness=2].> SoftwareSystem : "<color:#707070>Uses"
@enduml
```

Then I ran plantuml (installed from Ubuntu's repos) and opened the puml file, it shows the following error:

![struct-plantuml](https://user-images.githubusercontent.com/58572326/135179409-64a1ae5e-1545-4f40-9225-f7982b747023.png)

**Mermaid fails**

```
$ ./structurizr.sh export -workspace examples/getting-started/workspace.dsl -format mermaid
Exporting workspace from examples/getting-started/workspace.dsl
 - loading workspace from DSL
 - writing /home/user/bin/structurizr-cli-1.14.0/examples/getting-started/structurizr-SystemContext.mmd
 - finished

$ cat examples/getting-started/structurizr-SystemContext.mmd 
graph TB
  linkStyle default fill:#ffffff

  1["<div style='font-weight: bold'>User</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>A user of my software system.</div>"]
  style 1 fill:#08427b,stroke:#052e56,color:#ffffff
  2["<div style='font-weight: bold'>Software System</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>My software system.</div>"]
  style 2 fill:#1168bd,stroke:#0b4884,color:#ffffff

  1-. "<div>Uses</div><div style='font-size: 70%'></div>" .->2
```

When I paste the file contents at https://mermaid-js.github.io/mermaid-live-editor/ , I don't get a valid diagram:

![struct-mermaid](https://user-images.githubusercontent.com/58572326/135179417-eb3a7a02-0240-453c-9f95-bd1ad84e5a76.png)

**but dot works fine!!!**

```
$ ./structurizr.sh export -workspace examples/getting-started/workspace.dsl -format dot
Exporting workspace from examples/getting-started/workspace.dsl
 - loading workspace from DSL
 - writing /home/user/bin/structurizr-cli-1.14.0/examples/getting-started/structurizr-SystemContext.dot
 - finished

$ dot -T png examples/getting-started/structurizr-SystemContext.dot -o image.png
```
![struct-dot](https://user-images.githubusercontent.com/58572326/135179423-aa3b8204-ddd7-4276-b3b9-494ab3c13715.png)

I didn't try any other types because I've never even heard of them, sorry.

**Comment by simonbrowndotje** [comment]
The PlantUML definition works fine in the online editor ([example](http://www.plantuml.com/plantuml/uml/ZP9FQzj04CNl-oa6-zgwid4IOzOYVw2tG20jFSGvhBKZUR6qAtP6E6xfT--i4iUkQA2ho_9cz7upZxqcDf6xfbRik4Pu32NlJPJBWHWR-7oyt0NF-C9ASMY10sm2SsZ0keW5k-2LeftphOccWLyAWBR6Xhtp5PIc9XJ5n1ZsNyNcqVr4c6OYMInDL_CtCRwfNUKRz0m52YbATHzD-yDPti8iIzsDURb78bFXcqCI7qon4-KsH8lnBjGXQbt5qBLv3kEYFwUkHF-WvxTIMsSHIDWO-D3Y-KPfIUEh6hK-9lIQYpYaRM_5Fpbwszl3U3gzN6oiL8v8qSh-Y7OQLjHiCryivi8_qLgC5BpMtmdZHu1iCPzTRVuBS373YykquAilZ5QhvBpscYJ7vJJBdnxwohF-afHyxTV-1ZhfWL12Sm0wlWhgbvwCu7quGv1kwZsXP3zuHUUaGUaSUVzlq33mXFnRKogD09EdyLMMla-yTSNE8z5gzZp91zsmX94kKZRBj_vSVgUHkaPlkwR-0m00)). I don't use PlantUML myself, but perhaps the local version is different?

For Mermaid, you'll need to configure the security configuration, as described at [https://github.com/structurizr/cli/blob/master/docs/export.md](https://github.com/structurizr/cli/blob/master/docs/export.md).

**Comment by jerkstorecaller** [comment]
Oh snap, you're right. PlantUML works in the online version, and Mermaid works with securityLevel=loose. Sorry for the bother.
