### ISSUE TITLE
Export diagrams to PlantUML without a title.

### ISSUE THREAD

**Issue by wfouche** [structurizr/cli#57]
I'd like to export a workspace.dsl file to PUML diagram files but without the default diagram titles that are currently created, A -notitle option would resolve this issue. 

Titles could remain in the PUML file but only commented out if the -notitle option is specified.

````
'title ....
`````

The diagrams I created are included in an Asciidoc document where I specify document specific titles for the diagrams.

````
.My diagram title.
[plantuml,bi-diag1,svg]
----
include::c4-dsl/structurizr-Containers_BI.puml[]
----
````

**Comment by simonbrowndotje** [comment]
You can now do this by adding a view set property named `plantuml.title`; for example:

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }

    views {
        properties {
            plantuml.title false
        }
        
        systemContext softwareSystem {
            include *
            autolayout
        }

        theme default
    }
    
}
```
