### ISSUE TITLE
New release so structurizr/cli exports urls

### ISSUE THREAD

**Issue by pmorch** [structurizr/cli#59]
When using https://structurizr.com/dsl, a `url` in the input becomes a `[[link]]` in the output when using `-format plantuml/c4plantuml`. But not so with structurizr/cli.

I expect the output from https://structurizr.com/dsl to be the same as with structurizr/cli. If this the case, #58 would be possible using only built-in features.

To reproduce:

`cat bug/workspace.dsl`:
```
workspace {
    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System" {
            url "http://server/path/to/softaresystem.html"
        }

        user -> softwareSystem "Uses"
    }
    views {
        systemContext softwareSystem {
            include *
            autolayout
        }

        theme default
    }
}
```

If I put that in https://structurizr.com/dsl and render as C4-PlantUML, I get a line like:

```
System(SoftwareSystem, "Software System", "")[[http://server/path/to/softaresystem.html]]
```

But when using `structurizr-cli-1.15.0/structurizr.sh` the link is missing from the output:

```
$ ./structurizr-cli-1.15.0/structurizr.sh export -w bug/workspace.dsl -format plantuml/c4plantuml -output bug
$ grep ^System bug/structurizr-SoftwareSystem-SystemContext.puml 
System(SoftwareSystem, "Software System", "")
```

**Comment by simonbrowndotje** [comment]
Adding URLs to the C4-PlantUML export is [a recent change](https://github.com/structurizr/java-extensions/tree/master/structurizr-export), which is running on the demo page at https://structurizr.com/dsl but the CLI hasn't had a release yet. This will happen in the next week or so.

**Comment by pmorch** [comment]
Yeah, Just after you posted your answer, I discovered this commit https://github.com/structurizr/java-extensions/commit/e010920e155f03f6a6f55f6fc2cdb4b3a8895227 which is literally the HEAD commit. I guess I'm on the bleeding edge!

I've just compiled my own build/distributions/structurizr-cli-1.15.0.zip with structurizr-export:1.2.1 and it works flawlessly.

**Comment by simonbrowndotje** [comment]
v1.16.0 has now been released.
