### ISSUE TITLE
Export using plantuml exporter does not work

### ISSUE THREAD

**Issue by MTomBosch** [structurizr/cli#63]
On the Structurizr DSL demo page this workspace dsl leads to a plantuml error. Using the C4 plantuml exporter it works just fine.
I guess the reason is the incorrect location of the plantuml includes directive in the generated plantuml file.

```
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System"

        user -> softwareSystem "Uses"
    }

    views {
        systemContext softwareSystem {
            include *
            autolayout
        }
        
        properties {
            "plantuml.includes" "https://gist.githubusercontent.com/simonbrowndotje/b84878f8b87af3b76753ed871611c700/raw/b659b7ab9ac02a04725606f59138f37d2e67c265/styles.puml"
            "plantuml.legend" "true"
            "plantuml.title" "false"
        }
    }
    
}

```

**Comment by simonbrowndotje** [comment]
`AddRelTag` (in the included file) is a C4-PlanUML construct (see [Custom tags/stereotypes support and skinparam updates](https://github.com/plantuml-stdlib/C4-PlantUML#custom-tagsstereotypes-support-and-skinparam-updates)), so it'll only work in conjunction the C4-PlantUML macros.

**Comment by MTomBosch** [comment]
Ahh, I see.
Sorry for the inconveniences.
Will close it now.
