### ISSUE TITLE
feature request: generate json

### ISSUE THREAD

**Issue by im-bpriestman** [structurizr/cli#69]
It would be nice to be able to use the cli to generate a local json representation of a workspace.

Sample use-cases:

* I'm building a base workspace in the dsl, which I want to extend using code. The base workspace isn't very interesting until it's extended, so I want to put the json somewhere other than structurizr cloud. I want to do this as part of a build pipeline.
* I'm building a workspace in the dsl and do want to push it to structurizr cloud/in-house but I don't want anyone trying to edit the dsl outside of source control. Being able to export a json version of the workspace with the cli would enable to push that to structurizr, instead of the dsl.

I can create a json file easily enough by running sructurizr lite, and hitting the web console. I could automate this with frontend scripts, but using the cli would be more convenient.

**Comment by simonbrowndotje** [comment]
If you want to convert a DSL file to a JSON file, you can do this:

```
./structurizr.sh export -workspace workspace.dsl -format json
```

See https://github.com/structurizr/cli/blob/master/docs/export.md

**Comment by im-bpriestman** [comment]
🤦 Thanks, Simon. I missed that!
In fairness, the top-level description for the export command doesn't mention that.
Maybe: https://github.com/structurizr/cli/pull/70 ?
