### ISSUE TITLE
Export to png, svg file format

### ISSUE THREAD

**Issue by prlcutting** [structurizr/cli#74]
Is it possible to use the CLI to export out a png or svg file, just like we can interactively through the UI? Or is there some other way to automate the export of such image formats please? I see support for exporting various other "complex" formats, but not a basic image.

Thanks.

**Comment by simonbrowndotje** [comment]
Please see [the existing issues on this topic](https://github.com/structurizr/cli/issues?q=is%3Aissue+png).

**Comment by prlcutting** [comment]
Thanks Simon. I should have checked the existing issues first.

I'm new to Structurizr, but really like what I see so far. Great books too by the way - I appreciated the practical stance you took on things, and the conversational style of your writing.

Thanks, and keep up the good work!
