### ISSUE TITLE
export to json feature is changed/broken?

### ISSUE THREAD

**Issue by im-bpriestman** [structurizr/cli#83]
Hi,

I had a workflow set-up to chain structurizr workspaces. It relied on using the cli export command to take a dsl file and export it to json, to be used as by lite containers and as input for the next step.

Previously, `structurizr export -w workspace.dsl -f json -o .` would convert a `workspace.dsl` file to a `workspace.json` file, which could be read both by a lite container and consumed by other workspaces.

Now (since https://github.com/structurizr/cli/commit/29acf51ae207f2b1515feac1d5e8c037e7d8c451, I assume), it outputs a `structurizr.json` file containing invalid json (it's missing a final `}`).

There doesn't seem to be any way to specify the _name_ of the file exported, only the path destination. That's fine, I can adjust code to match that.

Is the invalid json intentional, though, or is this bug?

**Comment by simonbrowndotje** [comment]
Yes, it was broken ... apologies ... v1.20.1 is now available that resolves this.

**Comment by im-bpriestman** [comment]
Thanks. I'll wait for a new build of the lite container...

**Comment by simonbrowndotje** [comment]
You're welcome. But ... there's no need to wait for a new build of the Lite container. :-)
