### ISSUE TITLE
Allow user-defined format exporters as java classes

### ISSUE THREAD

**Issue by dgutson** [structurizr/cli#87]
Please allow users to specify a jar file as a format.  The jar file would contain a class that implements the abstract exporter.
```
--format jar/com.....
```

**Comment by simonbrowndotje** [comment]
A version of this feature is already available via the `-format` parameter in conjunction with a fully qualified Java class name. Do note that you'll need to ensure the class is available on the CLI classpath for this to work.

See https://github.com/structurizr/cli/blob/master/docs/export.md#options for more.

**Comment by dgutson** [comment]
Great, would you mind to add it to the command line help message?

**Comment by dgutson** [comment]
Sorry, I never noticed `fqcn` in the help.
