### ISSUE TITLE
BASH has wrong JAR version

### ISSUE THREAD

**Issue by n8behavior** [structurizr/cli#9]
Running `structurizr.sh` for 1.4.5 gives this error
```
Error: Unable to access jarfile /home/jack/source/github.com/hexad/passport-infra/bin/structurizr/structurizr-cli-1.4.4.jar
```
You forgot to update the **hard coded** version string in your script ;)

https://github.com/structurizr/cli/blob/master/etc/structurizr.sh#L3

-cheers

**Comment by simonbrowndotje** [comment]
Thanks!
