### ISSUE TITLE
Auto-formatter

### ISSUE THREAD

**Issue by kevinmichaelchen** [structurizr/cli#92]
Hello 👋🏼 C4 + Structurizr is going to be a great addition to our team!

I was wondering how feasible an auto-formatter would be.

I tried exporting to DSL and overwriting the file, but as I half-expected, it didn't fix any indentation.

(This is mostly a curiosity, not a deal-breaker or urgent).

**Comment by simonbrowndotje** [comment]
I have no plans to build an auto-formatter, but there are a couple of [VS Code extensions](https://github.com/structurizr/dsl#other-tooling-support) and an [IntelliJ plugin](https://github.com/dirkgroot/structurizr-dsl-intellij-plugin) that might provide this.
