### ISSUE TITLE
Use custom exporter for structurizr/cli docker 

### ISSUE THREAD

**Issue by qequ** [structurizr/cli#98]
Is there any way to load a custom exporter from [Structurizr's docker image](https://hub.docker.com/r/structurizr/cli)? Documentation only list the way using -export with the fully qualified class name but doesn't seem to be a way using the docker image getting the CLI classpath.

CC: @dgutson

**Comment by simonbrowndotje** [comment]
Not at this time ... you'd need to use the local installation (i.e. download the zipped version) or build your own Docker image that includes your additions.

**Comment by dgutson** [comment]
Ok let's close this, and try to get our exporter part of structurizr  :)

More on a specific issue.

**Comment by simonbrowndotje** [comment]
You can now place your JAR file(s) into a `plugins` folder next to your workspace DSL file, which will allow you to load custom exporters via the pre-built Docker image.

(this works in the same way as DSL plugins)

**Comment by dgutson** [comment]
This is so great and convenient.
Anyways I think our exporter might be a good contribution to structurizr.
Thanks!
